import { chromium } from 'playwright';
const BASE = 'http://127.0.0.1:3181';
const MK = 'local-test-only-management-key-0123456789abcdef';
const browser = await chromium.launch({ channel: process.env.UI_BROWSER_CHANNEL ?? 'msedge' });
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
const log = [];
page.on('console', (m) => log.push(`[console:${m.type()}] ${m.text().slice(0, 180)}`));
page.on('response', (r) => { if (r.url().includes('/api/')) log.push(`[api] ${r.request().method()} ${r.url().slice(BASE.length)} -> ${r.status()}`); });
page.on('framenavigated', (f) => log.push(`[nav] -> ${f.url()}`));

await page.goto(BASE + '/create', { waitUntil: 'networkidle' });
log.push(`[state] loaded /create, title: ${await page.title()}`);
await page.fill('#content', 'gated browser flow');
await page.getByRole('button', { name: 'Create Secret' }).click();
await page.waitForTimeout(2500);
log.push(`[state] url: ${page.url()}`);
log.push(`[state] key prompt: ${await page.isVisible('#instance-access-key')} | create disabled: ${await page.getByRole('button', { name: 'Create Secret' }).isDisabled()}`);
console.log(log.join('\n'));
await page.screenshot({ path: 'shot-gated.png', fullPage: true });
await browser.close();
